
##
 #
 # @Author Rizki Mufrizal <mufrizalrizki@gmail.com>
 # @Web <https://adhibarfan.github.io>
 # @Since Nov 16, 2016
 # @Time 19:35:19 PM
 # @Encoding ISO-8859-1
 # @Project Aplikasi-Perpustakaan
 # @Package Expression package is undefined on line 9, column 15 in Templates/Other/properties.properties.
 #
 ##
 
spring:
    profiles:
        active: development
        
    # spring datasource jpa
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/aplikasi_perpustakaan?autoReconnect=true
        username: root
        password: root
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
    
    # spring hibernate    
    jpa: 
        generate-ddl: true
        show-sql: true
        properties: 
            hibernate: 
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect

    # jackson config
    jackson: 
        serialization: 
            indent_output: true
            
# tomcat konfiguration
server: 
    tomcat: 
        access_log_enabled: true
        basedir: target/tomcat